### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by bevrard** [lbb00/figma-css-better#4]
Hello,

how can I use your plugin in figma?

Thanks

**Comment by lbb00** [comment]
First, you should install [tampermonkey](https://www.tampermonkey.net/) with your browser. Then click the install link in the readme of this repo, or search and install by [greasyfork](https://greasyfork.org).
Reload your Figma project page and select any element, it will show a copy button in the right menu.
Note that this plugin only works for converting px to rpx by px-to-viewport, rpx is used for the WeChat mini-program.

**Comment by bevrard** [comment]
Thanks for the answer :)
